const projects = [
  {
    id: 1,
    name: "Anarock Anacity",
    link: "/projects/anarock-anacity",
    position: "Full-Stack Development",
    year: "2025",
    image: "assets/img/project/service-wrok1.png",
    delay: "0.5s",
    col: "col-lg-7 col-md-6",
  },
  {
    id: 2,
    name: "SideHustl",
    link: "/projects/sidehustl",
    position: "Full-Stack Development",
    year: "2026",
    image: "assets/img/project/service-wrok2.png",
    delay: "0.7s",
    col: "col-lg-5 col-md-6",
  },
  {
    id: 3,
    name: "Lucidus",
    link: "/projects/lucidus",
    position: "Full-Stack Development",
    year: "2026",
    image: "assets/img/project/service-wrok3.png",
    delay: "0.9s",
    col: "col-lg-5 col-md-6",
  },
  {
    id: 4,
    name: "WEBC",
    link: "/projects/webc",
    position: "Frontend & Backend",
    year: "2023",
    image: "assets/img/project/service-wrok4.png",
    delay: "0.5s",
    col: "col-lg-7 col-md-6",
  },
  {
    id: 5,
    name: "DLF THRIVE",
    link: "/projects/lucidus",
    position: "Full-Stack Development",
    year: "2026",
    image: "assets/img/project/service-wrok1.png",
    delay: "0.9s",
    col: "col-lg-7 col-md-6",
  },
  {
    id: 6,
    name: "DLF GUILD",
    link: "/projects/lucidus",
    position: "Full-Stack Development",
    year: "2026",
    image: "assets/img/project/service-wrok3.png",
    delay: "0.9s",
    col: "col-lg-5 col-md-6",
  },
  {
    id: 5,
    name: "Renew",
    link: "/projects/lucidus",
    position: "Full-Stack Development",
    year: "2026",
    image: "assets/img/project/service-wrok1.png",
    delay: "0.9s",
    col: "col-lg-5 col-md-6",
  },
  {
    id: 6,
    name: "sugamya",
    link: "/projects/lucidus",
    position: "Full-Stack Development",
    year: "2026",
    image: "assets/img/project/service-wrok3.png",
    delay: "0.9s",
    col: "col-lg-7 col-md-6",
  },
];

export default projects;